// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  Identifier = 3,
  Keyword = 5,
  Number = 8,
  Prenumber = 7,
  Special = 10,
  DoubleEquals = 11,
  DoubleNotEquals = 12,
  Arrow = 13,
  Equals = 14,
  SpecialFunc = 16,
  Sorry = 18
