/* eslint-disable */
// @ts-nocheck

// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,for:10, const:10, return:10, continue:10, break:10, let:10, switch:10, match:10, extends:10, case:10, type:10, as:10, function:10, succ:16, N:20, Prop:20, never:20, any:20, trans:32, map:32, symm:32, excludedMiddle:32, replace:32, ring:32, neverElim:32, sorry:36}
export const parser = LRParser.deserialize({
  version: 14,
  states: "!^QYQPOOOOQO'#C`'#C`OOQO'#Cb'#CbOOQO'#Ce'#CeOOQO'#Ck'#CkOOQO'#Cm'#CmOOQO'#Cs'#CsOOQO'#Co'#CoQYQPOOOOQO-E6m-E6m",
  stateData: "}~OfOSPOS~ORUOTPOVQOWQOYROZUO[UO]UO^UO`SObTO~O",
  goto: "whPPPPiPiPPiPPPPPiPiPmPPPsTUOWQWORXWTVOW",
  nodeNames: "⚠ LineComment Program Identifier Keyword Keyword Number Prenumber Number Special Special DoubleEquals DoubleNotEquals Arrow Equals SpecialFunc SpecialFunc Sorry Sorry",
  maxTerm: 23,
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "$Z~RYXYqYZq]^qpqqqr!S!P!Q!g!Q![#U!_!`#^!c!}#{#T#o#{~vSf~XYqYZq]^qpqq~!VP!_!`!Y~!_P[~!_!`!b~!gO[~~!jP!P!Q!m~!rSP~OY!mZ;'S!m;'S;=`#O<%lO!m~#RP;=`<%l!m~#ZPV~!Q![#U~#cQ^~!_!`#i!`!a#v~#nPZ~!_!`#q~#vOZ~~#{O]~~$QRR~!Q![#{!c!}#{#T#o#{",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 3, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
